# Operasi Matematika & Numpy

### Latihan-4 (Operasi matriks)

In [ ]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [3]:
import numpy as np
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])
print (A)

[[1 2]
 [7 8]]


In [4]:
print (B)

[[3 5]
 [1 6]]


### 2 * A

In [5]:
X = 2*A
print ("Hasil dari 2 * A adalah ...")
print (X)

Hasil dari 2 * A adalah ...
[[ 2  4]
 [14 16]]


### 2 + A

In [6]:
Y = 2+A
print ("Hasil dari 2 + A adalah ...")
print (Y)

Hasil dari 2 + A adalah ...
[[ 3  4]
 [ 9 10]]


### A + B

In [7]:
C = A+B
print ("Hasil dari A + B adalah ...")
print (C)

Hasil dari A + B adalah ...
[[ 4  7]
 [ 8 14]]


### A - B

In [8]:
Z = A-B
print ("Hasil dari A - B adalah ...")
print (Z)

Hasil dari A - B adalah ...
[[-2 -3]
 [ 6  2]]


### Determinan A

In [9]:
det_A = np.linalg.det(A)
print ("Hasil dari Determinan A adalah ...")
print (det_A)

Hasil dari Determinan A adalah ...
-6.0


### Invers B = D

In [10]:
D = np.linalg.inv(B)
print ("Hasil dari Invers B adalah ...")
print (D)

Hasil dari Invers B adalah ...
[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


### Transpose Matriks D

In [11]:
D = np.array([[0.46153846, -0.38461538], [-0.07692308,  0.23076923]])

In [12]:
print (D)

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [13]:
Dt = D.transpose()
print ("Transpose Matriks D adalah...")
print (Dt)

Transpose Matriks D adalah...
[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


### nilai eigen dan vektor eigen dari A dan B

In [14]:
A = np.array([[1, 2], [7,8]])
print (A)

[[1 2]
 [7 8]]


In [15]:
print (np.linalg.eig(A))

(array([-0.62347538,  9.62347538]), array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]]))


In [16]:
e_val_A, e_vec_A = np.linalg.eig(A)

In [17]:
print (e_val_A)

[-0.62347538  9.62347538]


In [18]:
print (e_vec_A)

[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [19]:
B = np.array([[3, 5], [1,6]])
print (B)

[[3 5]
 [1 6]]


In [20]:
print (np.linalg.eig(B))

(array([1.8074176, 7.1925824]), array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]]))


In [21]:
e_val_B, e_vec_B = np.linalg.eig(B)

In [22]:
print (e_val_B)

[1.8074176 7.1925824]


In [23]:
print (e_vec_B)

[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]
